# Ensure npm directory is set up with proper permissions
sudo mkdir -p /var/www/.npm
sudo chown -R www-data:www-data /var/www/.npm

# Set up SSH directory with correct permissions, as root
mkdir -p /var/www/.ssh
chown -R www-data:www-data /var/www/.ssh
chmod 700 /var/www/.ssh

# Switch to www-data user
sudo su - www-data

# Give www-data a valid shell
sudo chsh -s /bin/bash www-data

# Generate new key pair
ssh-keygen -t ed25519 -C "your-server-name"

# Create/update authorized keys
touch /var/www/.ssh/authorized_keys
chmod 600 /var/www/.ssh/authorized_keys

# Copy the public key to authorized_keys
cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys

# Display the private key to copy to GitHub Secrets
cat ~/.ssh/id_ed25519

# Copy public key to GitHub as the deploy key at Settings -> Deploy Keys:
cat /var/www/.ssh/id_ed25519.pub

# Create or append GitHub's SSH key to known_hosts
ssh-keyscan github.com >> ~/.ssh/known_hosts

# Set proper permissions
chmod 644 ~/.ssh/known_hosts
